### ISSUE TITLE
Docs are not removed from stream

### ISSUE THREAD

**Issue by asorokin** [furkansarihan/firestore_collection#10]
Hi,

Thanks a lot for making this package, it's awesome. It is working as expected for my Firestore collection StreamBuilder in terms of pagination and adding new docs. However, when I remove a document, the stream doesn't trigger and don't update the StreamBuilder. I have two pages: one is the list of docs where I am using the StreamBuilder, and the second page is the doc detail screen where I can remove it, by using a button. Any idea how can I trigger the StreamBuilder update on docs removal? I also checked it with just a traditional Stream QuerySnapshot, and it is working as expected, but cannot get it working with the FirestoreCollection package. Appreciate your help on this. Thanks.

**Comment by azazadev** [comment]
@asorokin do you have try to use removeID ? ( _fireCollection.removeID(snapshot.data.elementAt(index).id) ), please check the example how we can remove doc from StreamBuilder https://github.com/furkansarihan/firestore_collection/blob/master/example/lib/main.dart
you can also call onItemRemoved to refresh your first page after delete

**Comment by asorokin** [comment]
Hi, I tried using removeID and it worked. Thank you!
