### ISSUE TITLE
Flutter : Bad state: Stream has already been listened to error when logout/login

### ISSUE THREAD

**Issue by azazadev** [furkansarihan/firestore_collection#4]
Hi,

after logout and when trying to logIn I got this error : **Flutter : Bad state: Stream has already been listened to**

calling dispose before logout and using BroadcastStream don't fix issue persist
@furkansarihan  Fix is to use BehaviorSubject class from RxDart library 
reference : https://stackoverflow.com/questions/53841750/flutter-stream-has-already-been-listened-to/55893532#55893532

**Comment by azazadev** [comment]
@furkansarihan please check this pull request : https://github.com/furkansarihan/firestore_collection/pull/5

**Comment by furkansarihan** [comment]
@azazadev  I just tested and merged your pull request. Good job,Thanks!

**Comment by azazadev** [comment]
@furkansarihan please update package on pub.dev

**Comment by furkansarihan** [comment]
@azazadev You can use package from [git dependency] for now.(https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages)

**Comment by furkansarihan** [comment]
You can use package from [git dependency](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages)

**Comment by azazadev** [comment]
> You can use package from [git dependency](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages)

sure, Thanks
